######################## default configuration ####################
baseURL = "http://example.org"
title = "مرجع آموزش کامپیوتر"
theme = "bookworm-light"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Image Processing ##############################
[imaging]
quality = "95"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true


############################## Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/line-awesome/css/line-awesome.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Vazirmatn:wght@500;600;700;800;900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# site variables
[params.variables]
font_primary = "Vazirmatn"
h1 = "64px"
h1_lg = "52px"
h1_md = "42px"
h2 = "38px"
h2_md = "30px"
h3 = "30px"
h3_md = "24px"
h4 = "24px"
h5 = "18px"
h6 = "16px"
white = "#ffffff"
black = "#000000"
dark = "#0b0b26"
gray = "#747577"
light = "#FAFAFA"
color_primary = "#01AD9F"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "50px"
favicon = "images/favicon.png"
# Meta data
description = "مرجع آموزش کامپیوتر - آموزش هایی که کمتر سایتی به آنها توجه میکند. برنامه نویسی سخت افزار و نرم افزار"
author = "NikiTv"
# contact form action
contact_form_action = "https://formspree.io/f/xdobygow" # contact form works with https://formspree.io Password for Site is: "4446627@Niki"
# search
search = true
# main section
mainSections = ["blog"]
# copyright
copyright = "طراحی و توسعه توسط جمعی از دوستان [NikiTv](https://nikitv.ir/)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Instagram feed
[params.instafeed]
enable = false
instagram_user = "bookworm"
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours
title = "Subscribe for our monthly newsletter."
input_placeholder = "Enter your email"

# cookies
[params.cookies]
enable = false
expire_days = 2


############################# Main Menu ########################
[[menu.main]]
name = "خانه"
url = "/"
weight = 1
  
[[menu.main]]
name = "درباره ما"
url = "about/"
weight = 3
  
[[menu.main]]
name = "تماس با ما"
url = "contact/"
weight = 4
  
# [[menu.main]]
# name = "Buy Premium"
# url = "https://gethugothemes.com/products/bookworm/"
# weight = 5

[[menu.main]]
weight = 6
url = "#"
name = "صفحات"
hasChildren = true

  [[menu.main]]
  parent = "صفحات"
  name = "نویسندگان"
  url = "author/"
  weight = 1
  
  [[menu.main]]
  parent = "صفحات"
  name = "تگ ها"
  url = "tags/"
  weight = 2
  
  [[menu.main]]
  parent = "صفحات"
  name = "دسته بندی"
  url = "categories/"
  weight = 3
  
  # [[menu.main]]
  # parent = "صفحات"
  # name = "Elements"
  # weight = 4
  # url = "elements/"
  
  [[menu.main]]
  parent = "صفحات"
  name = "حریم خصوصی"
  url = "privacy/"
  weight = 5
  
  [[menu.main]]
  parent = "صفحات"
  name = "قوانین و ضوابط"
  url = "terms-conditions/"
  weight = 6

############################# Footer Menu ########################
[[menu.footer]]
name = "درباره ما"
url = "about/"
weight = 1

[[menu.footer]]
name = "نویسندگان"
url = "author/"
weight = 2

[[menu.footer]]
name = "حریم خصوصی"
url = "privacy/"
weight = 3

[[menu.footer]]
name = "قوانین و ضوابط"
url = "terms-conditions/"
weight = 4

# Social Icons
[[params.social]]
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
url = "https://www.facebook.com/"

[[params.social]]
icon = "lab la-twitter" # https://icons8.com/line-awesome
url = "https://www.twitter.com/"

[[params.social]]
icon = "lab la-instagram" # https://icons8.com/line-awesome
url = "https://www.instagram.com/"

[[params.social]]
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
url = "https://www.linkedin.com/"